# Generated by Django 4.1 on 2022-08-21 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads',
            old_name='ad_id',
            new_name='Id',
        ),
        migrations.RenameField(
            model_name='categories',
            old_name='category_id',
            new_name='Id',
        ),
    ]
