# Generated by Django 4.1 on 2022-08-21 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_rename_ad_id_ads_id_rename_category_id_categories_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='Id',
            new_name='id',
        ),
    ]
